# Advanced Backtesting: Iterative Backtesting ("event-driven")

## A first Intuition on Iterative Backtesting (Part 1)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")

In [ ]:
data = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time")
data

In [ ]:
data = data.round(5)

In [ ]:
data.price.plot(figsize = (12, 8))
plt.show()

In [ ]:
data.spread.hist(bins = 100, figsize = (12, 8))
plt.show()

In [ ]:
for i in range(10):
    print(i)

In [ ]:
for bar in range(10): # interate over the first 10 bars/candles 
    print(bar, data.index[bar].date(), data.price.iloc[bar], data.spread.iloc[bar], sep = " | ")

In [ ]:
import time

In [ ]:
for bar in range(10):
    print(bar, data.index[bar].date(), data.price.iloc[bar], data.spread.iloc[bar], sep = " | ")
    time.sleep(1)

## A first Intuition on Iterative Backtesting (Part 2)

In [ ]:
data

In [ ]:
sma_s = 50
sma_l = 200

In [ ]:
data["SMA_S"] = data.price.rolling(sma_s).mean()
data["SMA_L"] = data.price.rolling(sma_l).mean()

In [ ]:
data.dropna(inplace = True)

In [ ]:
data

In [ ]:
position = 0 # we start with neutral position

In [ ]:
len(data)

In [ ]:
for bar in range(len(data)):
    if data["SMA_S"].iloc[bar] > data["SMA_L"].iloc[bar]:
        if position in [0, -1]:
            print("{}: Go Long  | Price: {} | Spread: {}".format(data.index[bar].date(), data.price.iloc[bar], data.spread.iloc[bar]))
            position = 1
    elif data["SMA_S"].iloc[bar] < data["SMA_L"].iloc[bar]:
        if position in [0, 1]:
            print("{}: Go Short | Price: {} | Spread: {}".format(data.index[bar].date(), data.price.iloc[bar], data.spread.iloc[bar]))
            position = -1

## Creating an Iterative Base Class (Part 1)

In [ ]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end].copy()
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)

In [ ]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [ ]:
bc.data

In [ ]:
bc.plot_data()

In [ ]:
bc.plot_data(cols = "spread")

## Creating an Iterative Base Class (Part 2)

In [ ]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        #returns = round(self.data.returns.iloc[bar], 5)
        return date, price, spread#, returns

In [ ]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [ ]:
bc.data

In [ ]:
bc.get_values(0)

In [ ]:
bc.get_values(100)

In [ ]:
bc.get_values(-1)

## Creating an Iterative Base Class (Part 3)

In [ ]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))

In [ ]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [ ]:
bc.data

In [ ]:
bc.print_current_balance(0)

In [ ]:
bc.print_current_balance(100)

In [ ]:
bc.print_current_balance(-1)

## Creating an Iterative Base Class (Part 4)

In [ ]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.units = 0
        self.trades = 0
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))
        
    def buy_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance -= units * price # reduce cash balance by "purchase price"
        self.units += units
        self.trades += 1
        print("{} |  Buying {} for {}".format(date, units, round(price, 5)))

In [ ]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [ ]:
bc.print_current_balance(0)

In [ ]:
bc.data

In [ ]:
bc.buy_instrument(0, units = 1000)

In [ ]:
bc.units

In [ ]:
bc.print_current_balance(0)

In [ ]:
100000 - 1000 * 1.31985

In [ ]:
bc.buy_instrument(1, amount = 5000)

In [ ]:
int(5000 / 1.32734)

In [ ]:
bc.print_current_balance(1)

## Creating an Iterative Base Class (Part 5)

In [4]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.units = 0
        self.trades = 0 
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))
        
    def buy_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance -= units * price # reduce cash balance by "purchase price"
        self.units += units
        self.trades += 1
        print("{} |  Buying {} for {}".format(date, units, round(price, 5)))
    
    def print_current_position_value(self, bar):
        date, price, spread = self.get_values(bar)
        cpv = self.units * price
        print("{} |  Current Position Value = {}".format(date, round(cpv, 2)))
    
    def print_current_nav(self, bar):
        date, price, spread = self.get_values(bar)
        nav = self.current_balance + self.units * price
        print("{} |  Net Asset Value = {}".format(date, round(nav, 2)))

In [5]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [6]:
bc.print_current_balance(0)

2006-12-31 | Current Balance: 100000

In [7]:
bc.buy_instrument(0, units = 1000)

2006-12-31 |  Buying 1000 for 1.31985

In [8]:
bc.units

1000

In [9]:
bc.print_current_balance(0)

2006-12-31 | Current Balance: 98680.15

In [10]:
bc.print_current_position_value(0)

2006-12-31 |  Current Position Value = 1319.85

In [12]:
bc.print_current_nav(0)

2006-12-31 |  Net Asset Value = 100000.0

In [13]:
bc.print_current_position_value(1)

2007-01-01 |  Current Position Value = 1327.34

In [14]:
bc.print_current_nav(1)

2007-01-01 |  Net Asset Value = 100007.49

In [15]:
bc.buy_instrument(1, amount = 5000)

2007-01-01 |  Buying 3766 for 1.32734

In [16]:
bc.print_current_balance(1)

2007-01-01 | Current Balance: 93681.39

In [17]:
bc.print_current_position_value(1)

2007-01-01 |  Current Position Value = 6326.1

In [22]:
bc.print_current_nav(1)

2007-01-01 |  Net Asset Value = 100007.49

In [31]:
bc.print_current_balance(2)

2007-04-22 | Current Balance: 93681.39

In [24]:
bc.print_current_position_value(2)

2007-01-02 |  Current Position Value = 6276.25

In [32]:
bc.print_current_nav(2)

2007-01-02 |  Net Asset Value = 99957.64

In [33]:
bc.print_current_nav(-1)

2020-06-29 |  Net Asset Value = 99035.08

In [34]:
bc.print_current_position_value(-1)

2020-06-29 |  Current Position Value = 5353.7

In [ ]:
bc.data

## Creating an Iterative Base Class (Part 6)

In [35]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.units = 0
        self.trades = 0 
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))
        
    def buy_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance -= units * price # reduce cash balance by "purchase price"
        self.units += units
        self.trades += 1
        print("{} |  Buying {} for {}".format(date, units, round(price, 5)))
    
    def sell_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance += units * price # increases cash balance by "purchase price"
        self.units -= units
        self.trades += 1
        print("{} |  Selling {} for {}".format(date, units, round(price, 5)))
    
    def print_current_position_value(self, bar):
        date, price, spread = self.get_values(bar)
        cpv = self.units * price
        print("{} |  Current Position Value = {}".format(date, round(cpv, 2)))
    
    def print_current_nav(self, bar):
        date, price, spread = self.get_values(bar)
        nav = self.current_balance + self.units * price
        print("{} |  Net Asset Value = {}".format(date, round(nav, 2)))

In [36]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [37]:
bc.buy_instrument(0, units = 10000) # go long 10,000 units

2006-12-31 |  Buying 10000 for 1.31985

In [38]:
bc.units

10000

In [ ]:
bc.print_current_position_value(1)

In [ ]:
bc.print_current_nav(1)

In [ ]:
bc.sell_instrument(1, units = 20000) # close long position and go short 10,000 units

In [ ]:
bc.units

In [ ]:
bc.print_current_balance(1) # cash balance increased, but...

In [ ]:
bc.print_current_position_value(1) # ... the current position value is negative

In [ ]:
bc.print_current_nav(1)

## Creating an Iterative Base Class (Part 7)

In [39]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.units = 0
        self.trades = 0 
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))
        
    def buy_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance -= units * price # reduce cash balance by "purchase price"
        self.units += units
        self.trades += 1
        print("{} |  Buying {} for {}".format(date, units, round(price, 5)))
    
    def sell_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance += units * price # increases cash balance by "purchase price"
        self.units -= units
        self.trades += 1
        print("{} |  Selling {} for {}".format(date, units, round(price, 5)))
    
    def print_current_position_value(self, bar):
        date, price, spread = self.get_values(bar)
        cpv = self.units * price
        print("{} |  Current Position Value = {}".format(date, round(cpv, 2)))
    
    def print_current_nav(self, bar):
        date, price, spread = self.get_values(bar)
        nav = self.current_balance + self.units * price
        print("{} |  Net Asset Value = {}".format(date, round(nav, 2)))
        
    def close_pos(self, bar):
        date, price, spread = self.get_values(bar)
        print(75 * "-")
        print("{} | +++ CLOSING FINAL POSITION +++".format(date))
        self.current_balance += self.units * price # closing final position (works with short and long!)
        print("{} | closing position of {} for {}".format(date, self.units, price))
        self.units = 0 # setting position to neutral
        self.trades += 1
        perf = (self.current_balance - self.initial_balance) / self.initial_balance * 100
        self.print_current_balance(bar)
        print("{} | net performance (%) = {}".format(date, round(perf, 2) ))
        print("{} | number of trades executed = {}".format(date, self.trades))
        print(75 * "-")

In [40]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000)

In [41]:
bc.buy_instrument(0, amount = 100000)

2006-12-31 |  Buying 75766 for 1.31985

In [42]:
bc.print_current_balance(0)

2006-12-31 | Current Balance: 0.24

In [43]:
bc.print_current_position_value(0)

2006-12-31 |  Current Position Value = 99999.76

In [44]:
bc.print_current_balance(-1)

2020-06-29 | Current Balance: 0.24

In [45]:
bc.print_current_position_value(-1)

2020-06-29 |  Current Position Value = 85108.71

In [46]:
bc.print_current_nav(-1)

2020-06-29 |  Net Asset Value = 85108.95

In [47]:
bc.close_pos(-1)

---------------------------------------------------------------------------
2020-06-29 | +++ CLOSING FINAL POSITION +++
2020-06-29 | closing position of 75766 for 1.12331
2020-06-29 | Current Balance: 85108.95
2020-06-29 | net performance (%) = -14.89
2020-06-29 | number of trades executed = 2
---------------------------------------------------------------------------

In [48]:
bc.data

                             price   spread   returns
time
2006-12-31 22:00:00+00:00  1.31985  0.00100       NaN
2007-01-01 22:00:00+00:00  1.32734  0.00015  0.005659
2007-01-02 22:00:00+00:00  1.31688  0.00015 -0.007912
2007-01-03 22:00:00+00:00  1.30845  0.00015 -0.006422
2007-01-04 22:00:00+00:00  1.30025  0.00100 -0.006287
...                            ...      ...       ...
2020-06-23 21:00:00+00:00  1.12507  0.00030 -0.005151
2020-06-24 21:00:00+00:00  1.12180  0.00023 -0.002911
2020-06-25 21:00:00+00:00  1.12184  0.00041  0.000036
2020-06-28 21:00:00+00:00  1.12424  0.00018  0.002137
2020-06-29 21:00:00+00:00  1.12331  0.00032 -0.000828

[4006 rows x 3 columns]

In [49]:
bc.data.price.iloc[-1] / bc.data.price.iloc[0] - 1

np.float64(-0.1489108610826988)

## Creating an Iterative Base Class (Part 8)

In [51]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount, use_spread = True):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.units = 0
        self.trades = 0
        self.use_spread = use_spread
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))
        
    def buy_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if self.use_spread:
            price += spread/2 # ask price
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance -= units * price # reduce cash balance by "purchase price"
        self.units += units
        self.trades += 1
        print("{} |  Buying {} for {}".format(date, units, round(price, 5)))
    
    def sell_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if self.use_spread:
            price -= spread/2 # bid price
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance += units * price # increases cash balance by "purchase price"
        self.units -= units
        self.trades += 1
        print("{} |  Selling {} for {}".format(date, units, round(price, 5)))
    
    def print_current_position_value(self, bar):
        date, price, spread = self.get_values(bar)
        cpv = self.units * price
        print("{} |  Current Position Value = {}".format(date, round(cpv, 2)))
    
    def print_current_nav(self, bar):
        date, price, spread = self.get_values(bar)
        nav = self.current_balance + self.units * price
        print("{} |  Net Asset Value = {}".format(date, round(nav, 2)))
        
    def close_pos(self, bar):
        date, price, spread = self.get_values(bar)
        print(75 * "-")
        print("{} | +++ CLOSING FINAL POSITION +++".format(date))
        self.current_balance += self.units * price # closing final position (works with short and long!)
        self.current_balance -= (abs(self.units) * spread/2 * self.use_spread) # substract half-spread costs
        print("{} | closing position of {} for {}".format(date, self.units, price))
        self.units = 0 # setting position to neutral
        self.trades += 1
        perf = (self.current_balance - self.initial_balance) / self.initial_balance * 100
        self.print_current_balance(bar)
        print("{} | net performance (%) = {}".format(date, round(perf, 2) ))
        print("{} | number of trades executed = {}".format(date, self.trades))
        print(75 * "-")

In [52]:
bc = IterativeBase("EURUSD", "2006-12-31", "2020-06-30", 100000, use_spread = True)

In [53]:
bc.buy_instrument(0, amount = 100000)

2006-12-31 |  Buying 75737 for 1.32035

In [54]:
bc.print_current_nav(0)

2006-12-31 |  Net Asset Value = 99962.13

In [55]:
bc.data

                             price   spread   returns
time
2006-12-31 22:00:00+00:00  1.31985  0.00100       NaN
2007-01-01 22:00:00+00:00  1.32734  0.00015  0.005659
2007-01-02 22:00:00+00:00  1.31688  0.00015 -0.007912
2007-01-03 22:00:00+00:00  1.30845  0.00015 -0.006422
2007-01-04 22:00:00+00:00  1.30025  0.00100 -0.006287
...                            ...      ...       ...
2020-06-23 21:00:00+00:00  1.12507  0.00030 -0.005151
2020-06-24 21:00:00+00:00  1.12180  0.00023 -0.002911
2020-06-25 21:00:00+00:00  1.12184  0.00041  0.000036
2020-06-28 21:00:00+00:00  1.12424  0.00018  0.002137
2020-06-29 21:00:00+00:00  1.12331  0.00032 -0.000828

[4006 rows x 3 columns]

In [56]:
bc.data.spread.iloc[0] / 2 * 75737

np.float64(37.8685)

In [57]:
bc.close_pos(-1)

---------------------------------------------------------------------------
2020-06-29 | +++ CLOSING FINAL POSITION +++
2020-06-29 | closing position of 75737 for 1.12331
2020-06-29 | Current Balance: 85064.66
2020-06-29 | net performance (%) = -14.94
2020-06-29 | number of trades executed = 2
---------------------------------------------------------------------------

## Iterative Backtesting of SMA Strategies

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")

In [59]:
class IterativeBase():

    def __init__(self, symbol, start, end, amount, use_spread = True):
        self.symbol = symbol
        self.start = start
        self.end = end
        self.initial_balance = amount
        self.current_balance = amount
        self.units = 0
        self.trades = 0
        self.position = 0
        self.use_spread = use_spread
        self.get_data()

    def get_data(self):
        raw = pd.read_csv("detailed.csv", parse_dates = ["time"], index_col = "time").dropna()
        raw = raw.loc[self.start:self.end]
        raw["returns"] = np.log(raw.price / raw.price.shift(1))
        self.data = raw

    def plot_data(self, cols = None):  
        if cols is None:
            cols = "price"
        self.data[cols].plot(figsize = (12, 8), title = self.symbol)
    
    def get_values(self, bar):
        date = str(self.data.index[bar].date())
        price = round(self.data.price.iloc[bar], 5)
        spread = round(self.data.spread.iloc[bar], 5)
        return date, price, spread
    
    def print_current_balance(self, bar):
        date, price, spread = self.get_values(bar)
        print("{} | Current Balance: {}".format(date, round(self.current_balance, 2)))
        
    def buy_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if self.use_spread:
            price += spread/2 # ask price
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance -= units * price # reduce cash balance by "purchase price"
        self.units += units
        self.trades += 1
        print("{} |  Buying {} for {}".format(date, units, round(price, 5)))
    
    def sell_instrument(self, bar, units = None, amount = None):
        date, price, spread = self.get_values(bar)
        if self.use_spread:
            price -= spread/2 # bid price
        if amount is not None: # use units if units are passed, otherwise calculate units
            units = int(amount / price)
        self.current_balance += units * price # increases cash balance by "purchase price"
        self.units -= units
        self.trades += 1
        print("{} |  Selling {} for {}".format(date, units, round(price, 5)))
    
    def print_current_position_value(self, bar):
        date, price, spread = self.get_values(bar)
        cpv = self.units * price
        print("{} |  Current Position Value = {}".format(date, round(cpv, 2)))
    
    def print_current_nav(self, bar):
        date, price, spread = self.get_values(bar)
        nav = self.current_balance + self.units * price
        print("{} |  Net Asset Value = {}".format(date, round(nav, 2)))
        
    def close_pos(self, bar):
        date, price, spread = self.get_values(bar)
        print(75 * "-")
        print("{} | +++ CLOSING FINAL POSITION +++".format(date))
        self.current_balance += self.units * price # closing final position (works with short and long!)
        self.current_balance -= (abs(self.units) * spread/2 * self.use_spread) # substract half-spread costs
        print("{} | closing position of {} for {}".format(date, self.units, price))
        self.units = 0 # setting position to neutral
        self.trades += 1
        perf = (self.current_balance - self.initial_balance) / self.initial_balance * 100
        self.print_current_balance(bar)
        print("{} | net performance (%) = {}".format(date, round(perf, 2) ))
        print("{} | number of trades executed = {}".format(date, self.trades))
        print(75 * "-")

In [60]:
class IterativeBacktest(IterativeBase):

    # helper method
    def go_long(self, bar, units = None, amount = None):
        if self.position == -1:
            self.buy_instrument(bar, units = -self.units) # if short position, go neutral first
        if units:
            self.buy_instrument(bar, units = units)
        elif amount:
            if amount == "all":
                amount = self.current_balance
            self.buy_instrument(bar, amount = amount) # go long

    # helper method
    def go_short(self, bar, units = None, amount = None):
        if self.position == 1:
            self.sell_instrument(bar, units = self.units) # if long position, go neutral first
        if units:
            self.sell_instrument(bar, units = units)
        elif amount:
            if amount == "all":
                amount = self.current_balance
            self.sell_instrument(bar, amount = amount) # go short

    def test_sma_strategy(self, SMA_S, SMA_L):
        
        # nice printout
        stm = "Testing SMA strategy | {} | SMA_S = {} & SMA_L = {}".format(self.symbol, SMA_S, SMA_L)
        print("-" * 75)
        print(stm)
        print("-" * 75)
        
        # reset 
        self.position = 0  # initial neutral position
        self.trades = 0  # no trades yet
        self.current_balance = self.initial_balance  # reset initial capital
        self.get_data() # reset dataset
        
        # prepare data
        self.data["SMA_S"] = self.data["price"].rolling(SMA_S).mean()
        self.data["SMA_L"] = self.data["price"].rolling(SMA_L).mean()
        self.data.dropna(inplace = True)

        # sma crossover strategy
        for bar in range(len(self.data)-1): # all bars (except the last bar)
            if self.data["SMA_S"].iloc[bar] > self.data["SMA_L"].iloc[bar]: # signal to go long
                if self.position in [0, -1]:
                    self.go_long(bar, amount = "all") # go long with full amount
                    self.position = 1  # long position
            elif self.data["SMA_S"].iloc[bar] < self.data["SMA_L"].iloc[bar]: # signal to go short
                if self.position in [0, 1]:
                    self.go_short(bar, amount = "all") # go short with full amount
                    self.position = -1 # short position
        self.close_pos(bar+1) # close position at the last bar

In [61]:
bc = IterativeBacktest("EURUSD", "2006-12-31", "2020-06-30", 100000, use_spread= True)

In [62]:
bc.data

                             price   spread   returns
time
2006-12-31 22:00:00+00:00  1.31985  0.00100       NaN
2007-01-01 22:00:00+00:00  1.32734  0.00015  0.005659
2007-01-02 22:00:00+00:00  1.31688  0.00015 -0.007912
2007-01-03 22:00:00+00:00  1.30845  0.00015 -0.006422
2007-01-04 22:00:00+00:00  1.30025  0.00100 -0.006287
...                            ...      ...       ...
2020-06-23 21:00:00+00:00  1.12507  0.00030 -0.005151
2020-06-24 21:00:00+00:00  1.12180  0.00023 -0.002911
2020-06-25 21:00:00+00:00  1.12184  0.00041  0.000036
2020-06-28 21:00:00+00:00  1.12424  0.00018  0.002137
2020-06-29 21:00:00+00:00  1.12331  0.00032 -0.000828

[4006 rows x 3 columns]

In [63]:
bc.test_sma_strategy(50, 200)

---------------------------------------------------------------------------
Testing SMA strategy | EURUSD | SMA_S = 50 & SMA_L = 200
---------------------------------------------------------------------------
2007-08-10 |  Buying 72998 for 1.36989
2008-08-28 |  Selling 72998 for 1.46685
2008-08-28 |  Selling 72998 for 1.46685
2009-04-28 |  Buying 72998 for 1.3276
2009-04-28 |  Buying 88311 for 1.3276
2010-01-20 |  Selling 88311 for 1.40833
2010-01-20 |  Selling 88311 for 1.40833
2010-09-27 |  Buying 88311 for 1.35862
2010-09-27 |  Buying 94774 for 1.35862
2011-01-12 |  Selling 94774 for 1.33626
2011-01-12 |  Selling 94774 for 1.33626
2011-01-30 |  Buying 94774 for 1.36946
2011-01-30 |  Buying 90178 for 1.36946
2011-09-10 |  Selling 90178 for 1.35825
2011-09-10 |  Selling 90178 for 1.35825
2012-10-08 |  Buying 90178 for 1.28857
2012-10-08 |  Buying 99931 for 1.28857
2013-04-15 |  Selling 99931 for 1.31755
2013-04-15 |  Selling 99931 for 1.31755
2013-08-04 |  Buying 99931 for 1.32592
2013-08-04 |  Buying 98669 for 1.32592
2014-07-06 |  Selling 98669 for 1.3603
2014-07-06 |  Selling 98669 for 1.3603
2015-09-30 |  Buying 98669 for 1.11953
2015-09-30 |  Buying 141110 for 1.11953
2015-11-24 |  Selling 141110 for 1.06232
2015-11-24 |  Selling 141110 for 1.06232
2016-03-22 |  Buying 141110 for 1.11821
2016-03-22 |  Buying 127006 for 1.11821
2016-10-23 |  Selling 127006 for 1.08806
2016-10-23 |  Selling 127006 for 1.08806
2017-05-23 |  Buying 127006 for 1.12197
2017-05-23 |  Buying 119330 for 1.12197
2018-06-06 |  Selling 119330 for 1.1796
2018-06-06 |  Selling 119330 for 1.1796
2020-06-25 |  Buying 119330 for 1.12204
2020-06-25 |  Buying 131572 for 1.12204
---------------------------------------------------------------------------
2020-06-29 | +++ CLOSING FINAL POSITION +++
2020-06-29 | closing position of 131572 for 1.12331
2020-06-29 | Current Balance: 147775.36
2020-06-29 | net performance (%) = 47.78
2020-06-29 | number of trades executed = 38
---------------------------------------------------------------------------

## Using Modules and adding Docstrings

In [64]:
import IterativeBacktest as IB

In [66]:
bc = IB.IterativeBacktest("EURUSD", "2006-12-31", "2020-06-30", 100000, use_spread = True)

In [67]:
bc.data

                             price   spread   returns
time
2006-12-31 22:00:00+00:00  1.31985  0.00100       NaN
2007-01-01 22:00:00+00:00  1.32734  0.00015  0.005659
2007-01-02 22:00:00+00:00  1.31688  0.00015 -0.007912
2007-01-03 22:00:00+00:00  1.30845  0.00015 -0.006422
2007-01-04 22:00:00+00:00  1.30025  0.00100 -0.006287
...                            ...      ...       ...
2020-06-23 21:00:00+00:00  1.12507  0.00030 -0.005151
2020-06-24 21:00:00+00:00  1.12180  0.00023 -0.002911
2020-06-25 21:00:00+00:00  1.12184  0.00041  0.000036
2020-06-28 21:00:00+00:00  1.12424  0.00018  0.002137
2020-06-29 21:00:00+00:00  1.12331  0.00032 -0.000828

[4006 rows x 3 columns]

In [68]:
bc.test_sma_strategy(50, 200)

---------------------------------------------------------------------------
Testing SMA strategy | EURUSD | SMA_S = 50 & SMA_L = 200
---------------------------------------------------------------------------
2007-08-10 |  Buying 72998 for 1.36989
2008-08-28 |  Selling 72998 for 1.46685
2008-08-28 |  Selling 72998 for 1.46685
2009-04-28 |  Buying 72998 for 1.3276
2009-04-28 |  Buying 88311 for 1.3276
2010-01-20 |  Selling 88311 for 1.40833
2010-01-20 |  Selling 88311 for 1.40833
2010-09-27 |  Buying 88311 for 1.35862
2010-09-27 |  Buying 94774 for 1.35862
2011-01-12 |  Selling 94774 for 1.33626
2011-01-12 |  Selling 94774 for 1.33626
2011-01-30 |  Buying 94774 for 1.36946
2011-01-30 |  Buying 90178 for 1.36946
2011-09-10 |  Selling 90178 for 1.35825
2011-09-10 |  Selling 90178 for 1.35825
2012-10-08 |  Buying 90178 for 1.28857
2012-10-08 |  Buying 99931 for 1.28857
2013-04-15 |  Selling 99931 for 1.31755
2013-04-15 |  Selling 99931 for 1.31755
2013-08-04 |  Buying 99931 for 1.32592
2013-08-04 |  Buying 98669 for 1.32592
2014-07-06 |  Selling 98669 for 1.3603
2014-07-06 |  Selling 98669 for 1.3603
2015-09-30 |  Buying 98669 for 1.11953
2015-09-30 |  Buying 141110 for 1.11953
2015-11-24 |  Selling 141110 for 1.06232
2015-11-24 |  Selling 141110 for 1.06232
2016-03-22 |  Buying 141110 for 1.11821
2016-03-22 |  Buying 127006 for 1.11821
2016-10-23 |  Selling 127006 for 1.08806
2016-10-23 |  Selling 127006 for 1.08806
2017-05-23 |  Buying 127006 for 1.12197
2017-05-23 |  Buying 119330 for 1.12197
2018-06-06 |  Selling 119330 for 1.1796
2018-06-06 |  Selling 119330 for 1.1796
2020-06-25 |  Buying 119330 for 1.12204
2020-06-25 |  Buying 131572 for 1.12204
---------------------------------------------------------------------------
2020-06-29 | +++ CLOSING FINAL POSITION +++
2020-06-29 | closing position of 131572 for 1.12331
2020-06-29 | Current Balance: 147775.36
2020-06-29 | net performance (%) = 47.78
2020-06-29 | number of trades executed = 38
---------------------------------------------------------------------------

## Adding Contrarian and Bollinger Strategy to the Framework

In [70]:
import IterativeBacktest as IB

In [71]:
bc = IB.IterativeBacktest("EURUSD", "2006-12-31", "2020-06-30", 100000, use_spread= True)

In [72]:
bc.data

                             price   spread   returns
time
2006-12-31 22:00:00+00:00  1.31985  0.00100       NaN
2007-01-01 22:00:00+00:00  1.32734  0.00015  0.005659
2007-01-02 22:00:00+00:00  1.31688  0.00015 -0.007912
2007-01-03 22:00:00+00:00  1.30845  0.00015 -0.006422
2007-01-04 22:00:00+00:00  1.30025  0.00100 -0.006287
...                            ...      ...       ...
2020-06-23 21:00:00+00:00  1.12507  0.00030 -0.005151
2020-06-24 21:00:00+00:00  1.12180  0.00023 -0.002911
2020-06-25 21:00:00+00:00  1.12184  0.00041  0.000036
2020-06-28 21:00:00+00:00  1.12424  0.00018  0.002137
2020-06-29 21:00:00+00:00  1.12331  0.00032 -0.000828

[4006 rows x 3 columns]

__Contrarian__

In [73]:
bc.test_con_strategy(window = 3)

---------------------------------------------------------------------------
Testing Contrarian strategy | EURUSD | Window = 3
---------------------------------------------------------------------------
2007-01-03 |  Buying 76421 for 1.30852
2007-01-14 |  Selling 76421 for 1.29364
2007-01-14 |  Selling 76421 for 1.29364
2007-01-15 |  Buying 76421 for 1.29185
2007-01-15 |  Buying 76634 for 1.29185
2007-01-16 |  Selling 76634 for 1.29372
2007-01-16 |  Selling 76634 for 1.29372
2007-01-21 |  Buying 76634 for 1.29507
2007-01-21 |  Buying 76476 for 1.29507
2007-01-22 |  Selling 76476 for 1.30258
2007-01-22 |  Selling 76476 for 1.30258
2007-01-24 |  Buying 76476 for 1.29328
2007-01-24 |  Buying 77575 for 1.29328
2007-01-28 |  Selling 77575 for 1.29561
2007-01-28 |  Selling 77575 for 1.29561
2007-02-01 |  Buying 77575 for 1.29666
2007-02-01 |  Buying 77449 for 1.29666
2007-02-05 |  Selling 77449 for 1.29841
2007-02-05 |  Selling 77449 for 1.29841
2007-02-09 |  Buying 77449 for 1.30135
2007-02-09 |  Buying 77100 for 1.30135
2007-02-12 |  Selling 77100 for 1.30375
2007-02-12 |  Selling 77100 for 1.30375
2007-02-20 |  Buying 77100 for 1.31403
2007-02-20 |  Buying 75893 for 1.31403
2007-02-22 |  Selling 75893 for 1.31615
2007-02-22 |  Selling 75893 for 1.31615
2007-02-28 |  Buying 75893 for 1.31875
2007-02-28 |  Buying 75594 for 1.31875
2007-03-07 |  Selling 75594 for 1.31334
2007-03-07 |  Selling 75594 for 1.31334
2007-03-08 |  Buying 75594 for 1.31205
2007-03-08 |  Buying 75743 for 1.31205
2007-03-11 |  Selling 75743 for 1.31886
2007-03-11 |  Selling 75743 for 1.31886
2007-03-18 |  Buying 75743 for 1.33034
2007-03-18 |  Buying 74435 for 1.33034
2007-03-20 |  Selling 74435 for 1.33849
2007-03-20 |  Selling 74435 for 1.33849
2007-03-22 |  Buying 74435 for 1.32885
2007-03-22 |  Buying 75515 for 1.32885
2007-03-26 |  Selling 75515 for 1.33521
2007-03-26 |  Selling 75515 for 1.33521
2007-04-02 |  Buying 75515 for 1.33313
2007-04-02 |  Buying 75751 for 1.33313
2007-04-04 |  Selling 75751 for 1.34292
2007-04-04 |  Selling 75751 for 1.34292
2007-04-07 |  Buying 75751 for 1.33805
2007-04-07 |  Buying 76302 for 1.33805
2007-04-09 |  Selling 76302 for 1.34384
2007-04-09 |  Selling 76302 for 1.34384
2007-04-21 |  Buying 76302 for 1.36035
2007-04-21 |  Buying 74450 for 1.36035
2007-04-23 |  Selling 74450 for 1.36383
2007-04-23 |  Selling 74450 for 1.36383
2007-04-29 |  Buying 74450 for 1.36486
2007-04-29 |  Buying 74338 for 1.36486
2007-05-05 |  Selling 74338 for 1.35985
2007-05-05 |  Selling 74338 for 1.35985
2007-05-07 |  Buying 74338 for 1.3543
2007-05-07 |  Buying 74947 for 1.3543
2007-05-12 |  Selling 74947 for 1.3532
2007-05-12 |  Selling 74947 for 1.3532
2007-05-15 |  Buying 74947 for 1.35163
2007-05-15 |  Buying 75121 for 1.35163
2007-05-19 |  Selling 75121 for 1.3514
2007-05-19 |  Selling 75121 for 1.3514
2007-05-20 |  Buying 75121 for 1.34696
2007-05-20 |  Buying 75617 for 1.34696
2007-05-26 |  Selling 75617 for 1.3444
2007-05-26 |  Selling 75617 for 1.3444
2007-05-29 |  Buying 75617 for 1.34301
2007-05-29 |  Buying 75773 for 1.34301
2007-05-30 |  Selling 75773 for 1.34526
2007-05-30 |  Selling 75773 for 1.34526
2007-06-02 |  Buying 75773 for 1.3446
2007-06-02 |  Buying 75847 for 1.3446
2007-06-03 |  Selling 75847 for 1.34886
2007-06-03 |  Selling 75847 for 1.34886
2007-06-06 |  Buying 75847 for 1.34346
2007-06-06 |  Buying 76457 for 1.34346
2007-06-14 |  Selling 76457 for 1.33837
2007-06-14 |  Selling 76457 for 1.33837
2007-06-20 |  Buying 76457 for 1.33904
2007-06-20 |  Buying 76381 for 1.33904
2007-06-21 |  Selling 76381 for 1.3464
2007-06-21 |  Selling 76381 for 1.3464
2007-06-25 |  Buying 76381 for 1.3455
2007-06-25 |  Buying 76483 for 1.3455
2007-06-28 |  Selling 76483 for 1.3536
2007-06-28 |  Selling 76483 for 1.3536
2007-07-04 |  Buying 76483 for 1.35991
2007-07-04 |  Buying 75773 for 1.35991
2007-07-05 |  Selling 75773 for 1.36228
2007-07-05 |  Selling 75773 for 1.36228
2007-07-15 |  Buying 75773 for 1.37734
2007-07-15 |  Buying 74116 for 1.37734
2007-07-17 |  Selling 74116 for 1.38027
2007-07-17 |  Selling 74116 for 1.38027
2007-07-23 |  Buying 74116 for 1.38239
2007-07-23 |  Buying 73889 for 1.38239
2007-07-30 |  Selling 73889 for 1.36834
2007-07-30 |  Selling 73889 for 1.36834
2007-08-06 |  Buying 73889 for 1.37376
2007-08-06 |  Buying 73306 for 1.37376
2007-08-11 |  Selling 73306 for 1.36833
2007-08-11 |  Selling 73306 for 1.36833
2007-08-12 |  Buying 73306 for 1.36137
2007-08-12 |  Buying 74055 for 1.36137
2007-08-18 |  Selling 74055 for 1.3478
2007-08-18 |  Selling 74055 for 1.3478
2007-08-20 |  Buying 74055 for 1.34671
2007-08-20 |  Buying 74175 for 1.34671
2007-08-21 |  Selling 74175 for 1.35416
2007-08-21 |  Selling 74175 for 1.35416
2007-08-27 |  Buying 74175 for 1.36046
2007-08-27 |  Buying 73488 for 1.36046
2007-08-28 |  Selling 73488 for 1.36764
2007-08-28 |  Selling 73488 for 1.36764
2007-08-29 |  Buying 73488 for 1.3626
2007-08-29 |  Buying 74032 for 1.3626
2007-08-30 |  Selling 74032 for 1.36245
2007-08-30 |  Selling 74032 for 1.36245
2007-09-01 |  Buying 74032 for 1.36375
2007-09-01 |  Buying 73891 for 1.36375
2007-09-04 |  Selling 73891 for 1.36459
2007-09-04 |  Selling 73891 for 1.36459
2007-09-15 |  Buying 73891 for 1.38725
2007-09-15 |  Buying 71477 for 1.38725
2007-09-17 |  Selling 71477 for 1.3983
2007-09-17 |  Selling 71477 for 1.3983
2007-10-01 |  Buying 71477 for 1.4155
2007-10-01 |  Buying 69739 for 1.4155
2007-10-06 |  Selling 69739 for 1.41354
2007-10-06 |  Selling 69739 for 1.41354
2007-10-07 |  Buying 69739 for 1.4049
2007-10-07 |  Buying 70596 for 1.4049
2007-10-09 |  Selling 70596 for 1.41454
2007-10-09 |  Selling 70596 for 1.41454
2007-10-13 |  Buying 70596 for 1.4181
2007-10-13 |  Buying 70241 for 1.4181
2007-10-14 |  Selling 70241 for 1.42046
2007-10-14 |  Selling 70241 for 1.42046
2007-10-15 |  Buying 70241 for 1.41736
2007-10-15 |  Buying 70548 for 1.41736
2007-10-16 |  Selling 70548 for 1.42072
2007-10-16 |  Selling 70548 for 1.42072
2007-10-21 |  Buying 70548 for 1.41822
2007-10-21 |  Buying 70796 for 1.41822
2007-10-24 |  Selling 70796 for 1.43238
2007-10-24 |  Selling 70796 for 1.43238
2007-11-11 |  Buying 70796 for 1.4533
2007-11-11 |  Buying 68757 for 1.4533
2007-11-14 |  Selling 68757 for 1.4612
2007-11-14 |  Selling 68757 for 1.4612
2007-11-22 |  Buying 68757 for 1.48425
2007-11-22 |  Buying 66621 for 1.48425
2007-11-25 |  Selling 66621 for 1.48714
2007-11-25 |  Selling 66621 for 1.48714
2007-11-26 |  Buying 66621 for 1.48292
2007-11-26 |  Buying 66999 for 1.48292
2007-11-27 |  Selling 66999 for 1.48411
2007-11-27 |  Selling 66999 for 1.48411
2007-11-28 |  Buying 66999 for 1.47442
2007-11-28 |  Buying 67880 for 1.47442
2007-12-03 |  Selling 67880 for 1.47577
2007-12-03 |  Selling 67880 for 1.47577
2007-12-04 |  Buying 67880 for 1.4612
2007-12-04 |  Buying 69233 for 1.4612
2007-12-08 |  Selling 69233 for 1.46503
2007-12-08 |  Selling 69233 for 1.46503
2007-12-10 |  Buying 69233 for 1.46556
2007-12-10 |  Buying 69183 for 1.46556
2007-12-11 |  Selling 69183 for 1.4706
2007-12-11 |  Selling 69183 for 1.4706
2007-12-12 |  Buying 69183 for 1.46344
2007-12-12 |  Buying 69859 for 1.46344
2007-12-23 |  Selling 69859 for 1.43885
2007-12-23 |  Selling 69859 for 1.43885
2007-12-30 |  Buying 69859 for 1.4597
2007-12-30 |  Buying 67863 for 1.4597
2008-01-02 |  Selling 67863 for 1.47506
2008-01-02 |  Selling 67863 for 1.47506
2008-01-06 |  Buying 67863 for 1.46958
2008-01-06 |  Buying 68368 for 1.46958
2008-01-09 |  Selling 68368 for 1.48034
2008-01-09 |  Selling 68368 for 1.48034
2008-01-15 |  Buying 68368 for 1.4653
2008-01-15 |  Buying 69771 for 1.4653
2008-01-21 |  Selling 69771 for 1.46289
2008-01-21 |  Selling 69771 for 1.46289
2008-02-02 |  Buying 69771 for 1.4811
2008-02-02 |  Buying 68056 for 1.4811
2008-02-10 |  Selling 68056 for 1.4518
2008-02-10 |  Selling 68056 for 1.4518
2008-03-09 |  Buying 68056 for 1.5344
2008-03-09 |  Buying 60728 for 1.5344
2008-03-11 |  Selling 60728 for 1.55508
2008-03-11 |  Selling 60728 for 1.55508
2008-03-17 |  Buying 60728 for 1.56246
2008-03-17 |  Buying 60154 for 1.56246
2008-03-24 |  Selling 60154 for 1.56498
2008-03-24 |  Selling 60154 for 1.56498
2008-03-29 |  Buying 60154 for 1.5807
2008-03-29 |  Buying 58957 for 1.5807
2008-03-30 |  Selling 58957 for 1.57878
2008-03-30 |  Selling 58957 for 1.57878
2008-03-31 |  Buying 58957 for 1.56146
2008-03-31 |  Buying 60265 for 1.56146
2008-04-03 |  Selling 60265 for 1.57325
2008-04-03 |  Selling 60265 for 1.57325
2008-04-07 |  Buying 60265 for 1.5712
2008-04-07 |  Buying 60421 for 1.5712
2008-04-08 |  Selling 60421 for 1.58312
2008-04-08 |  Selling 60421 for 1.58312
2008-04-12 |  Buying 60421 for 1.56985
2008-04-12 |  Buying 61443 for 1.56985
2008-04-13 |  Selling 61443 for 1.58318
2008-04-13 |  Selling 61443 for 1.58318
2008-04-14 |  Buying 61443 for 1.57898
2008-04-14 |  Buying 61769 for 1.57898
2008-04-15 |  Selling 61769 for 1.5947
2008-04-15 |  Selling 61769 for 1.5947
2008-04-19 |  Buying 61769 for 1.5811
2008-04-19 |  Buying 62832 for 1.5811
2008-04-20 |  Selling 62832 for 1.59118
2008-04-20 |  Selling 62832 for 1.59118
2008-04-23 |  Buying 62832 for 1.56824
2008-04-23 |  Buying 64669 for 1.56824
2008-04-27 |  Selling 64669 for 1.56576
2008-04-27 |  Selling 64669 for 1.56576
2008-04-28 |  Buying 64669 for 1.55726
2008-04-28 |  Buying 65374 for 1.55726
2008-04-29 |  Selling 65374 for 1.56222
2008-04-29 |  Selling 65374 for 1.56222
2008-04-30 |  Buying 65374 for 1.54758
2008-04-30 |  Buying 66610 for 1.54758
2008-05-04 |  Selling 66610 for 1.5496
2008-05-04 |  Selling 66610 for 1.5496
2008-05-06 |  Buying 66610 for 1.53928
2008-05-06 |  Buying 67504 for 1.53928
2008-05-10 |  Selling 67504 for 1.54505
2008-05-10 |  Selling 67504 for 1.54505
2008-05-12 |  Buying 67504 for 1.5475
2008-05-12 |  Buying 67291 for 1.5475
2008-05-13 |  Selling 67291 for 1.54734
2008-05-13 |  Selling 67291 for 1.54734
2008-05-14 |  Buying 67291 for 1.5448
2008-05-14 |  Buying 67511 for 1.5448
2008-05-15 |  Selling 67511 for 1.55717
2008-05-15 |  Selling 67511 for 1.55717
2008-05-24 |  Buying 67511 for 1.57727
2008-05-24 |  Buying 65791 for 1.57727
2008-05-25 |  Selling 65791 for 1.57694
2008-05-25 |  Selling 65791 for 1.57694
2008-05-26 |  Buying 65791 for 1.56917
2008-05-26 |  Buying 66442 for 1.56917
2008-06-01 |  Selling 66442 for 1.55362
2008-06-01 |  Selling 66442 for 1.55362
2008-06-02 |  Buying 66442 for 1.54448
2008-06-02 |  Buying 67229 for 1.54448
2008-06-04 |  Selling 67229 for 1.55934
2008-06-04 |  Selling 67229 for 1.55934
2008-06-08 |  Buying 67229 for 1.56466
2008-06-08 |  Buying 66773 for 1.56466
2008-06-15 |  Selling 66773 for 1.5477
2008-06-15 |  Selling 66773 for 1.5477
2008-06-23 |  Buying 66773 for 1.55688
2008-06-23 |  Buying 65986 for 1.55688
2008-06-24 |  Selling 65986 for 1.56661
2008-06-24 |  Selling 65986 for 1.56661
2008-06-29 |  Buying 65986 for 1.57568
2008-06-29 |  Buying 65226 for 1.57568
2008-07-01 |  Selling 65226 for 1.58817
2008-07-01 |  Selling 65226 for 1.58817
2008-07-02 |  Buying 65226 for 1.57044
2008-07-02 |  Buying 66700 for 1.57044
2008-07-06 |  Selling 66700 for 1.57248
2008-07-06 |  Selling 66700 for 1.57248
2008-07-07 |  Buying 66700 for 1.56714
2008-07-07 |  Buying 67155 for 1.56714
2008-07-08 |  Selling 67155 for 1.57422
2008-07-08 |  Selling 67155 for 1.57422
2008-07-13 |  Buying 67155 for 1.59084
2008-07-13 |  Buying 65752 for 1.59084
2008-07-18 |  Selling 65752 for 1.58427
2008-07-18 |  Selling 65752 for 1.58427
2008-07-19 |  Buying 65752 for 1.58477
2008-07-19 |  Buying 65710 for 1.58477
2008-07-20 |  Selling 65710 for 1.59218
2008-07-20 |  Selling 65710 for 1.59218
2008-07-21 |  Buying 65710 for 1.5784
2008-07-21 |  Buying 66859 for 1.5784
2008-07-26 |  Selling 66859 for 1.57045
2008-07-26 |  Selling 66859 for 1.57045
2008-07-28 |  Buying 66859 for 1.55887
2008-07-28 |  Buying 67852 for 1.55887
2008-08-03 |  Selling 67852 for 1.55756
2008-08-03 |  Selling 67852 for 1.55756
2008-08-04 |  Buying 67852 for 1.54548
2008-08-04 |  Buying 68914 for 1.54548
2008-08-18 |  Selling 68914 for 1.47746
2008-08-18 |  Selling 68914 for 1.47746
2008-08-24 |  Buying 68914 for 1.4755
2008-08-24 |  Buying 69096 for 1.4755
2008-08-28 |  Selling 69096 for 1.46685
2008-08-28 |  Selling 69096 for 1.46685
2008-08-30 |  Buying 69096 for 1.46975
2008-08-30 |  Buying 68823 for 1.46975
2008-09-11 |  Selling 68823 for 1.4221
2008-09-11 |  Selling 68823 for 1.4221
2008-09-15 |  Buying 68823 for 1.41327
2008-09-15 |  Buying 69683 for 1.41327
2008-09-17 |  Selling 69683 for 1.43479
2008-09-17 |  Selling 69683 for 1.43479
2008-09-24 |  Buying 69683 for 1.46103
2008-09-24 |  Buying 67180 for 1.46103
2008-10-08 |  Selling 67180 for 1.36029
2008-10-08 |  Selling 67181 for 1.36029
2008-10-09 |  Buying 67181 for 1.34127
2008-10-09 |  Buying 69086 for 1.34127
2008-10-12 |  Selling 69086 for 1.35818
2008-10-12 |  Selling 69086 for 1.35818
2008-10-14 |  Buying 69086 for 1.35007
2008-10-14 |  Buying 69916 for 1.35007
2008-10-27 |  Selling 69916 for 1.26809
2008-10-27 |  Selling 69916 for 1.26809
2008-11-01 |  Buying 69916 for 1.27529
2008-11-01 |  Buying 69126 for 1.27529
2008-11-03 |  Selling 69126 for 1.29795
2008-11-03 |  Selling 69126 for 1.29795
2008-11-06 |  Buying 69126 for 1.27234
2008-11-06 |  Buying 71909 for 1.27234
2008-11-08 |  Selling 71909 for 1.2811
2008-11-08 |  Selling 71909 for 1.2811
2008-11-10 |  Buying 71909 for 1.2525
2008-11-10 |  Buying 75193 for 1.2525
2008-11-12 |  Selling 75193 for 1.27675
2008-11-12 |  Selling 75193 for 1.27675
2008-11-16 |  Buying 75193 for 1.26522
2008-11-16 |  Buying 76563 for 1.26522
2008-11-17 |  Selling 76563 for 1.26174
2008-11-17 |  Selling 76563 for 1.26174
2008-11-18 |  Buying 76563 for 1.24904
2008-11-18 |  Buying 78119 for 1.24904
2008-11-22 |  Selling 78119 for 1.25858
2008-11-22 |  Selling 78119 for 1.25858
2008-11-26 |  Buying 78119 for 1.29057
2008-11-26 |  Buying 74246 for 1.29057
2008-12-01 |  Selling 74246 for 1.27132
2008-12-01 |  Selling 74246 for 1.27132
2008-12-06 |  Buying 74246 for 1.27346
2008-12-06 |  Buying 73996 for 1.27346
2008-12-07 |  Selling 73996 for 1.29625
2008-12-07 |  Selling 73996 for 1.29625
2008-12-18 |  Buying 73996 for 1.39178
2008-12-18 |  Buying 63837 for 1.39178
2008-12-22 |  Selling 63837 for 1.3925
2008-12-22 |  Selling 63837 for 1.3925
2008-12-28 |  Buying 63837 for 1.39291
2008-12-28 |  Buying 63800 for 1.39291
2008-12-29 |  Selling 63800 for 1.4057
2008-12-29 |  Selling 63800 for 1.4057
2008-12-30 |  Buying 63800 for 1.39809
2008-12-30 |  Buying 64494 for 1.39809
2008-12-31 |  Selling 64494 for 1.4039
2008-12-31 |  Selling 64494 for 1.4039
2009-01-01 |  Buying 64494 for 1.39261
2009-01-01 |  Buying 65540 for 1.39261
2009-01-07 |  Selling 65540 for 1.37015
2009-01-07 |  Selling 65540 for 1.37015
2009-01-08 |  Buying 65540 for 1.34817
2009-01-08 |  Buying 67677 for 1.34817
2009-01-15 |  Selling 67677 for 1.32617
2009-01-15 |  Selling 67677 for 1.32617
2009-01-18 |  Buying 67677 for 1.307
2009-01-18 |  Buying 69661 for 1.307
2009-01-22 |  Selling 69661 for 1.29829
2009-01-22 |  Selling 69661 for 1.29829
2009-01-24 |  Buying 69661 for 1.29711
2009-01-24 |  Buying 69788 for 1.29711
2009-01-25 |  Selling 69788 for 1.31874
2009-01-25 |  Selling 69788 for 1.31874
2009-01-28 |  Buying 69788 for 1.2955
2009-01-28 |  Buying 72291 for 1.2955
2009-02-02 |  Selling 72291 for 1.30396
2009-02-02 |  Selling 72291 for 1.30396
2009-02-04 |  Buying 72291 for 1.27928
2009-02-04 |  Buying 75081 for 1.27928
2009-02-06 |  Selling 75081 for 1.29351
2009-02-06 |  Selling 75081 for 1.29351
2009-02-09 |  Buying 75081 for 1.29152
2009-02-09 |  Buying 75312 for 1.29152
2009-02-19 |  Selling 75312 for 1.28214
2009-02-19 |  Selling 75312 for 1.28214
2009-02-24 |  Buying 75312 for 1.27246
2009-02-24 |  Buying 76457 for 1.27246
2009-02-25 |  Selling 76457 for 1.27433
2009-02-25 |  Selling 76457 for 1.27433
2009-02-26 |  Buying 76457 for 1.26736
2009-02-26 |  Buying 77298 for 1.26736
2009-03-03 |  Selling 77298 for 1.26599
2009-03-03 |  Selling 77298 for 1.26599
2009-03-04 |  Buying 77298 for 1.25412
2009-03-04 |  Buying 78760 for 1.25412
2009-03-05 |  Selling 78760 for 1.26494
2009-03-05 |  Selling 78760 for 1.26494
2009-03-07 |  Buying 78760 for 1.26588
2009-03-07 |  Buying 78643 for 1.26588
2009-03-08 |  Selling 78643 for 1.26104
2009-03-08 |  Selling 78643 for 1.26104
2009-03-14 |  Buying 78643 for 1.28905
2009-03-14 |  Buying 75224 for 1.28905
2009-03-15 |  Selling 75224 for 1.29662
2009-03-15 |  Selling 75224 for 1.29662
2009-03-21 |  Buying 75224 for 1.36292
2009-03-21 |  Buying 67905 for 1.36292
2009-03-22 |  Selling 67905 for 1.36308
2009-03-22 |  Selling 67905 for 1.36308
2009-03-23 |  Buying 67905 for 1.34696
2009-03-23 |  Buying 69530 for 1.34696
2009-03-31 |  Selling 69530 for 1.32478
2009-03-31 |  Selling 69530 for 1.32478
2009-04-05 |  Buying 69530 for 1.34178
2009-04-05 |  Buying 67768 for 1.34178
2009-04-12 |  Selling 67768 for 1.3366
2009-04-12 |  Selling 67768 for 1.3366
2009-04-15 |  Buying 67768 for 1.31883
2009-04-15 |  Buying 69594 for 1.31883
2009-04-22 |  Selling 69594 for 1.31424
2009-04-22 |  Selling 69594 for 1.31424
2009-04-26 |  Buying 69594 for 1.30394
2009-04-26 |  Buying 70692 for 1.30394
2009-04-28 |  Selling 70692 for 1.3273
2009-04-28 |  Selling 70692 for 1.3273
2009-05-01 |  Buying 70692 for 1.32755
2009-05-01 |  Buying 70666 for 1.32755
2009-05-02 |  Selling 70666 for 1.32655
2009-05-02 |  Selling 70666 for 1.32655
2009-05-06 |  Buying 70666 for 1.3396
2009-05-06 |  Buying 69289 for 1.3396
2009-05-07 |  Selling 69289 for 1.36283
2009-05-07 |  Selling 69289 for 1.36283
2009-05-12 |  Buying 69289 for 1.3601
2009-05-12 |  Buying 69567 for 1.3601
2009-05-13 |  Selling 69567 for 1.36382
2009-05-13 |  Selling 69567 for 1.36382
2009-05-14 |  Buying 69567 for 1.35003
2009-05-14 |  Buying 70988 for 1.35003
2009-05-18 |  Selling 70988 for 1.36286
2009-05-18 |  Selling 70988 for 1.36286
2009-05-25 |  Buying 70988 for 1.39872
2009-05-25 |  Buying 67347 for 1.39872
2009-05-28 |  Selling 67347 for 1.41525
2009-05-28 |  Selling 67347 for 1.41525
2009-06-04 |  Buying 67347 for 1.39733
2009-06-04 |  Buying 69075 for 1.39733
2009-06-08 |  Selling 69075 for 1.4063
2009-06-08 |  Selling 69075 for 1.4063
2009-06-11 |  Buying 69075 for 1.40215
2009-06-11 |  Buying 69483 for 1.40215
2009-06-13 |  Selling 69483 for 1.39935
2009-06-13 |  Selling 69483 for 1.39935
2009-06-14 |  Buying 69483 for 1.38038
2009-06-14 |  Buying 71392 for 1.38038
2009-06-17 |  Selling 71392 for 1.38996
2009-06-17 |  Selling 71392 for 1.38996
2009-06-21 |  Buying 71392 for 1.38668
2009-06-21 |  Buying 71729 for 1.38668
2009-06-22 |  Selling 71729 for 1.40762
2009-06-22 |  Selling 71729 for 1.40762
2009-06-23 |  Buying 71729 for 1.39301
2009-06-23 |  Buying 73233 for 1.39301
2009-06-24 |  Selling 73233 for 1.39872
2009-06-24 |  Selling 73233 for 1.39872
2009-06-25 |  Buying 73233 for 1.40605
2009-06-25 |  Buying 72469 for 1.40605
2009-06-26 |  Selling 72469 for 1.4052
2009-06-26 |  Selling 72469 for 1.4052
2009-06-29 |  Buying 72469 for 1.40337
2009-06-29 |  Buying 72658 for 1.40337
2009-06-30 |  Selling 72658 for 1.41407
2009-06-30 |  Selling 72658 for 1.41407
2009-07-01 |  Buying 72658 for 1.40048
2009-07-01 |  Buying 74069 for 1.40048
2009-07-05 |  Selling 74069 for 1.39825
2009-07-05 |  Selling 74069 for 1.39825
2009-07-06 |  Buying 74069 for 1.39249
2009-07-06 |  Buying 74681 for 1.39249
2009-07-08 |  Selling 74681 for 1.40186
2009-07-08 |  Selling 74681 for 1.40186
2009-07-12 |  Buying 74681 for 1.39789
2009-07-12 |  Buying 75105 for 1.39789
2009-07-13 |  Selling 75105 for 1.39647
2009-07-13 |  Selling 75105 for 1.39647
2009-07-18 |  Buying 75105 for 1.41025
2009-07-18 |  Buying 73637 for 1.41025
2009-07-19 |  Selling 73637 for 1.42305
2009-07-19 |  Selling 73637 for 1.42305
2009-07-22 |  Buying 73637 for 1.41434
2009-07-22 |  Buying 74544 for 1.41434
2009-07-25 |  Selling 74544 for 1.42222
2009-07-25 |  Selling 74544 for 1.42222

__Bollinger__

In [74]:
bc.test_boll_strategy(50, 2)

---------------------------------------------------------------------------
Testing Bollinger Bands Strategy | EURUSD | SMA = 50 & dev = 2
---------------------------------------------------------------------------
2007-02-26 |  Selling 75519 for 1.32416
2007-05-16 |  Buying 75519 for 1.34947
2007-06-07 |  Buying 73318 for 1.33784
2007-06-28 |  Selling 73318 for 1.3536
2007-07-01 |  Selling 72850 for 1.36229
2007-08-12 |  Buying 72850 for 1.36137
2007-09-17 |  Selling 71022 for 1.3983
2007-12-13 |  Buying 71022 for 1.44347
2008-02-25 |  Selling 64180 for 1.49738
2008-04-25 |  Buying 64180 for 1.5632
2008-07-01 |  Selling 57852 for 1.58817
2008-07-23 |  Buying 57852 for 1.56784
2008-08-06 |  Buying 60717 for 1.5326
2008-09-21 |  Selling 60717 for 1.47754
2008-10-01 |  Buying 64905 for 1.38221
2008-11-24 |  Selling 64905 for 1.30635
2008-12-10 |  Selling 63508 for 1.33508
2009-01-11 |  Buying 63508 for 1.33632
2009-03-17 |  Selling 62877 for 1.3472
2009-04-16 |  Buying 62877 for 1.30497
2009-05-19 |  Selling 63402 for 1.37792
2009-07-06 |  Buying 63402 for 1.39249
2009-08-02 |  Selling 59981 for 1.44114
2009-08-16 |  Buying 59981 for 1.40842
2009-09-07 |  Selling 61064 for 1.4477
2009-10-27 |  Buying 61064 for 1.47068
2009-11-24 |  Selling 57489 for 1.51332
2009-12-03 |  Buying 57489 for 1.48628
2009-12-10 |  Buying 60570 for 1.462
2010-03-11 |  Selling 60570 for 1.37636
2010-03-23 |  Buying 62614 for 1.33142
2010-04-10 |  Selling 62614 for 1.36537
2010-04-26 |  Buying 64886 for 1.31757
2010-06-19 |  Selling 64886 for 1.24424
2010-07-14 |  Selling 62347 for 1.29492
2010-08-12 |  Buying 62347 for 1.2759
2010-09-21 |  Selling 61112 for 1.34047
2010-11-08 |  Buying 61112 for 1.37737
2010-11-15 |  Buying 59054 for 1.34901
2010-12-30 |  Selling 59054 for 1.33786
2011-01-06 |  Buying 61186 for 1.29123
2011-01-12 |  Selling 61186 for 1.33626
2011-01-20 |  Selling 60046 for 1.36163
2011-05-05 |  Buying 60046 for 1.4319
2011-07-10 |  Buying 55267 for 1.40302
2011-07-20 |  Selling 55267 for 1.44229
2011-09-04 |  Buying 56539 for 1.40984
2011-10-11 |  Selling 56539 for 1.37901
2011-10-26 |  Selling 54961 for 1.41861
2011-11-08 |  Buying 54961 for 1.3544
2011-11-24 |  Buying 61519 for 1.32475
2012-01-23 |  Selling 61519 for 1.30351
2012-05-05 |  Buying 61600 for 1.30179
2012-06-28 |  Selling 61600 for 1.26593
2012-07-05 |  Buying 63457 for 1.2289
2012-08-04 |  Selling 63457 for 1.23949
2012-08-22 |  Selling 62606 for 1.25633
2012-10-28 |  Buying 62606 for 1.29048
2012-11-04 |  Buying 59794 for 1.27966
2012-11-22 |  Selling 59794 for 1.2973
2012-12-13 |  Selling 58942 for 1.31605
2013-02-19 |  Buying 58942 for 1.3285
2013-03-05 |  Buying 59251 for 1.2968
2013-04-08 |  Selling 59251 for 1.30816
2013-06-05 |  Selling 58524 for 1.32443
2013-06-24 |  Buying 58524 for 1.30818
2013-09-17 |  Selling 58031 for 1.35205
2013-10-31 |  Buying 58031 for 1.34879
2014-03-05 |  Selling 56751 for 1.38588
2014-04-02 |  Buying 56751 for 1.37212
2014-05-12 |  Buying 57958 for 1.3705
2014-06-29 |  Selling 57958 for 1.36904
2014-07-21 |  Buying 58917 for 1.34674
2015-04-27 |  Selling 58917 for 1.09808
2015-05-05 |  Selling 57020 for 1.13463
2015-05-25 |  Buying 57020 for 1.08732
2015-07-16 |  Buying 62219 for 1.08316
2015-08-11 |  Selling 62219 for 1.1159
2015-08-20 |  Selling 60994 for 1.1383
2015-09-21 |  Buying 60994 for 1.11286
2015-10-22 |  Buying 64416 for 1.10194
2015-12-08 |  Selling 64416 for 1.10241
2016-02-02 |  Selling 63966 for 1.11017
2016-02-25 |  Buying 63966 for 1.09367
2016-05-26 |  Buying 64835 for 1.11156
2016-06-02 |  Selling 64835 for 1.13652
2016-06-26 |  Buying 66829 for 1.10261
2016-07-28 |  Selling 66829 for 1.11696
2016-08-17 |  Selling 65753 for 1.13522
2016-09-15 |  Buying 65753 for 1.11616
2016-10-10 |  Buying 68656 for 1.10549
2016-11-03 |  Selling 68656 for 1.11366
2016-11-13 |  Buying 71196 for 1.07394
2017-01-12 |  Selling 71196 for 1.06384
2017-03-26 |  Selling 69731 for 1.08618
2017-03-29 |  Buying 69731 for 1.06755
2017-04-23 |  Selling 70901 for 1.08659
2017-09-25 |  Buying 70901 for 1.1796
2017-10-25 |  Buying 60445 for 1.16544
2017-11-13 |  Selling 60445 for 1.17955
2017-12-28 |  Selling 59411 for 1.20009
2018-02-27 |  Buying 59411 for 1.21968
2018-04-24 |  Buying 57661 for 1.21633
2018-07-05 |  Selling 57661 for 1.17427
2018-08-08 |  Buying 58736 for 1.15278
2018-08-23 |  Selling 58736 for 1.1619
2018-10-23 |  Buying 59902 for 1.13927
2018-12-19 |  Selling 59902 for 1.14444
2019-01-06 |  Selling 59748 for 1.1474
2019-01-17 |  Buying 59748 for 1.13659
2019-02-10 |  Buying 61366 for 1.12767
2019-02-25 |  Selling 61366 for 1.1388
2019-03-06 |  Buying 62423 for 1.11952
2019-03-19 |  Selling 62423 for 1.14116
2019-04-23 |  Buying 63838 for 1.11588
2019-06-02 |  Selling 63838 for 1.12408
2019-06-06 |  Selling 63337 for 1.13296
2019-06-13 |  Buying 63337 for 1.12145
2019-06-20 |  Selling 63771 for 1.13668
2019-07-04 |  Buying 63771 for 1.12305
2019-07-30 |  Buying 66222 for 1.10772
2019-10-15 |  Selling 66222 for 1.10708
2019-10-17 |  Selling 65659 for 1.11658
2019-11-07 |  Buying 65659 for 1.10238
2019-12-29 |  Selling 66306 for 1.11974
2020-01-16 |  Buying 66306 for 1.10929
2020-02-05 |  Buying 68231 for 1.09831
2020-02-27 |  Selling 68231 for 1.10227
2020-03-08 |  Selling 65771 for 1.1435
2020-03-16 |  Buying 65771 for 1.09984
2020-03-18 |  Buying 73007 for 1.0695
2020-03-25 |  Selling 73007 for 1.10311
2020-05-27 |  Selling 72714 for 1.10755
---------------------------------------------------------------------------
2020-06-29 | +++ CLOSING FINAL POSITION +++
2020-06-29 | closing position of -72714 for 1.12331
2020-06-29 | Current Balance: 79377.26
2020-06-29 | net performance (%) = -20.62
2020-06-29 | number of trades executed = 134
---------------------------------------------------------------------------