# First Steps with the OANDA API

## Connecting to the API / Server

In [1]:
import pandas as pd
import tpqoa

In [2]:
api = tpqoa.tpqoa("oanda.cfg")

In [3]:
api.get_account_summary()

{'id': '101-011-37633556-002',
 'alias': 'Konto2',
 'currency': 'EUR',
 'balance': '99745.9395',
 'createdByUserID': 37633556,
 'createdTime': '2025-11-10T13:42:43.019655832Z',
 'guaranteedStopLossOrderMode': 'ALLOWED',
 'pl': '-91.8254',
 'resettablePL': '-91.8254',
 'resettablePLTime': '0',
 'financing': '-162.2351',
 'commission': '0.0',
 'guaranteedExecutionFees': '0.0',
 'marginRate': '0.03333333333333',
 'openTradeCount': 0,
 'openPositionCount': 0,
 'pendingOrderCount': 0,
 'hedgingEnabled': False,
 'unrealizedPL': '0.0',
 'NAV': '99745.9395',
 'marginUsed': '0.0',
 'marginAvailable': '99745.9395',
 'positionValue': '0.0',
 'marginCloseoutUnrealizedPL': '0.0',
 'marginCloseoutNAV': '99745.9395',
 'marginCloseoutMarginUsed': '0.0',
 'marginCloseoutPercent': '0.0',
 'marginCloseoutPositionValue': '0.0',
 'withdrawalLimit': '99745.9395',
 'marginCallMarginUsed': '0.0',
 'marginCallPercent': '0.0',
 'lastTransactionID': '773'}

In [4]:
api.account_type

'practice'

In [5]:
api.account_id

'101-011-37633556-002'

In [6]:
api.get_instruments()

[('AUD/CAD', 'AUD_CAD'),
 ('AUD/CHF', 'AUD_CHF'),
 ('AUD/HKD', 'AUD_HKD'),
 ('AUD/JPY', 'AUD_JPY'),
 ('AUD/NZD', 'AUD_NZD'),
 ('AUD/SGD', 'AUD_SGD'),
 ('AUD/USD', 'AUD_USD'),
 ('Australia 200', 'AU200_AUD'),
 ('Bitcoin', 'BTC_USD'),
 ('Bitcoin Cash', 'BCH_USD'),
 ('Brent Crude Oil', 'BCO_USD'),
 ('Bund', 'DE10YB_EUR'),
 ('CAD/CHF', 'CAD_CHF'),
 ('CAD/HKD', 'CAD_HKD'),
 ('CAD/JPY', 'CAD_JPY'),
 ('CAD/SGD', 'CAD_SGD'),
 ('CHF/HKD', 'CHF_HKD'),
 ('CHF/JPY', 'CHF_JPY'),
 ('CHF/ZAR', 'CHF_ZAR'),
 ('China A50', 'CN50_USD'),
 ('China H Shares', 'CHINAH_HKD'),
 ('Copper', 'XCU_USD'),
 ('Corn', 'CORN_USD'),
 ('EUR/AUD', 'EUR_AUD'),
 ('EUR/CAD', 'EUR_CAD'),
 ('EUR/CHF', 'EUR_CHF'),
 ('EUR/CZK', 'EUR_CZK'),
 ('EUR/DKK', 'EUR_DKK'),
 ('EUR/GBP', 'EUR_GBP'),
 ('EUR/HKD', 'EUR_HKD'),
 ('EUR/HUF', 'EUR_HUF'),
 ('EUR/JPY', 'EUR_JPY'),
 ('EUR/NOK', 'EUR_NOK'),
 ('EUR/NZD', 'EUR_NZD'),
 ('EUR/PLN', 'EUR_PLN'),
 ('EUR/SEK', 'EUR_SEK'),
 ('EUR/SGD', 'EUR_SGD'),
 ('EUR/TRY', 'EUR_TRY'),
 ('EUR/USD', 'EUR_USD'),
 ('EUR/ZAR', 'EUR_ZAR'),
 ('Ether', 'ETH_USD'),
 ('Europe 50', 'EU50_EUR'),
 ('France 40', 'FR40_EUR'),
 ('GBP/AUD', 'GBP_AUD'),
 ('GBP/CAD', 'GBP_CAD'),
 ('GBP/CHF', 'GBP_CHF'),
 ('GBP/HKD', 'GBP_HKD'),
 ('GBP/JPY', 'GBP_JPY'),
 ('GBP/NZD', 'GBP_NZD'),
 ('GBP/PLN', 'GBP_PLN'),
 ('GBP/SGD', 'GBP_SGD'),
 ('GBP/USD', 'GBP_USD'),
 ('GBP/ZAR', 'GBP_ZAR'),
 ('Germany 30', 'DE30_EUR'),
 ('Gold', 'XAU_USD'),
 ('Gold/AUD', 'XAU_AUD'),
 ('Gold/CAD', 'XAU_CAD'),
 ('Gold/CHF', 'XAU_CHF'),
 ('Gold/EUR', 'XAU_EUR'),
 ('Gold/GBP', 'XAU_GBP'),
 ('Gold/HKD', 'XAU_HKD'),
 ('Gold/JPY', 'XAU_JPY'),
 ('Gold/NZD', 'XAU_NZD'),
 ('Gold/SGD', 'XAU_SGD'),
 ('Gold/Silver', 'XAU_XAG'),
 ('HKD/JPY', 'HKD_JPY'),
 ('Hong Kong 33', 'HK33_HKD'),
 ('Japan 225', 'JP225_USD'),
 ('Japan 225 (JPY)', 'JP225Y_JPY'),
 ('Litecoin', 'LTC_USD'),
 ('NZD/CAD', 'NZD_CAD'),
 ('NZD/CHF', 'NZD_CHF'),
 ('NZD/HKD', 'NZD_HKD'),
 ('NZD/JPY', 'NZD_JPY'),
 ('NZD/SGD', 'NZD_SGD'),
 ('NZD/USD', 'NZD_USD'),
 ('Natural Gas', 'NATGAS_USD'),
 ('Netherlands 25', 'NL25_EUR'),
 ('Palladium', 'XPD_USD'),
 ('Platinum', 'XPT_USD'),
 ('SGD/CHF', 'SGD_CHF'),
 ('SGD/JPY', 'SGD_JPY'),
 ('Silver', 'XAG_USD'),
 ('Silver/AUD', 'XAG_AUD'),
 ('Silver/CAD', 'XAG_CAD'),
 ('Silver/CHF', 'XAG_CHF'),
 ('Silver/EUR', 'XAG_EUR'),
 ('Silver/GBP', 'XAG_GBP'),
 ('Silver/HKD', 'XAG_HKD'),
 ('Silver/JPY', 'XAG_JPY'),
 ('Silver/NZD', 'XAG_NZD'),
 ('Silver/SGD', 'XAG_SGD'),
 ('Singapore 30', 'SG30_SGD'),
 ('Soybeans', 'SOYBN_USD'),
 ('Spain 35', 'ESPIX_EUR'),
 ('Sugar', 'SUGAR_USD'),
 ('Switzerland 20', 'CH20_CHF'),
 ('TRY/JPY', 'TRY_JPY'),
 ('UK 100', 'UK100_GBP'),
 ('UK 10Y Gilt', 'UK10YB_GBP'),
 ('US 10Y T-Note', 'USB10Y_USD'),
 ('US 2Y T-Note', 'USB02Y_USD'),
 ('US 5Y T-Note', 'USB05Y_USD'),
 ('US Nas 100', 'NAS100_USD'),
 ('US Russ 2000', 'US2000_USD'),
 ('US SPX 500', 'SPX500_USD'),
 ('US T-Bond', 'USB30Y_USD'),
 ('US Wall St 30', 'US30_USD'),
 ('USD/CAD', 'USD_CAD'),
 ('USD/CHF', 'USD_CHF'),
 ('USD/CNH', 'USD_CNH'),
 ('USD/CZK', 'USD_CZK'),
 ('USD/DKK', 'USD_DKK'),
 ('USD/HKD', 'USD_HKD'),
 ('USD/HUF', 'USD_HUF'),
 ('USD/JPY', 'USD_JPY'),
 ('USD/MXN', 'USD_MXN'),
 ('USD/NOK', 'USD_NOK'),
 ('USD/PLN', 'USD_PLN'),
 ('USD/SEK', 'USD_SEK'),
 ('USD/SGD', 'USD_SGD'),
 ('USD/THB', 'USD_THB'),
 ('USD/TRY', 'USD_TRY'),
 ('USD/ZAR', 'USD_ZAR'),
 ('West Texas Oil', 'WTICO_USD'),
 ('Wheat', 'WHEAT_USD'),
 ('ZAR/JPY', 'ZAR_JPY')]

In [7]:
instr = api.get_instruments()

In [8]:
len(instr)

127

In [9]:
instr[8]

('Bitcoin', 'BTC_USD')

## Getting Historical Data (Part 1)

In [10]:
import pandas as pd
import tpqoa
import warnings
warnings.filterwarnings('ignore')

In [11]:
api = tpqoa.tpqoa("oanda.cfg")

In [12]:
help(api.get_history)

Help on method get_history in module tpqoa.tpqoa:

get_history(instrument, start, end, granularity, price, localize=True) method of tpqoa.tpqoa.tpqoa instance
    Retrieves historical data for instrument.

    Parameters
    ==========
    instrument: string
        valid instrument name
    start, end: datetime, str
        Python datetime or string objects for start and end
    granularity: string
        a string like 'S5', 'M1' or 'D'
    price: string
        one of 'A' (ask), 'B' (bid) or 'M' (middle)

    Returns
    =======
    data: pd.DataFrame
        pandas DataFrame object with data

In [13]:
api.get_history(instrument = "EUR_USD", start = "2021-01-09", end = "2024-09-09",
                granularity = "D", price = "B")

                           o        h        l        c  volume  complete
time
2021-01-10 22:00:00  1.22140  1.22224  1.21315  1.21497  104515      True
2021-01-11 22:00:00  1.21500  1.22091  1.21363  1.22069   98206      True
2021-01-12 22:00:00  1.22059  1.22223  1.21389  1.21571   94061      True
2021-01-13 22:00:00  1.21495  1.21779  1.21101  1.21496  104506      True
2021-01-14 22:00:00  1.21501  1.21619  1.20714  1.20754   91612      True
...                      ...      ...      ...      ...     ...       ...
2024-09-02 21:00:00  1.10664  1.10722  1.10256  1.10426  101767      True
2024-09-03 21:00:00  1.10420  1.10944  1.10370  1.10823  100247      True
2024-09-04 21:00:00  1.10821  1.11190  1.10740  1.11099  101712      True
2024-09-05 21:00:00  1.11089  1.11547  1.10649  1.10846  136886      True
2024-09-08 21:00:00  1.10798  1.10903  1.10331  1.10343   82539      True

[953 rows x 6 columns]

In [14]:
df = api.get_history(instrument = "EUR_USD", start = "2021-01-09", end = "2024-09-09",granularity = "D", price = "B")

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 953 entries, 2021-01-10 22:00:00 to 2024-09-08 21:00:00
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   o         953 non-null    float64
 1   h         953 non-null    float64
 2   l         953 non-null    float64
 3   c         953 non-null    float64
 4   volume    953 non-null    int64
 5   complete  953 non-null    bool
dtypes: bool(1), float64(4), int64(1)
memory usage: 45.6 KB

In [16]:
api.get_history(instrument = "EUR_USD", start = "2024-09-09", end = "2024-09-09",
                granularity = "D", price = "A")

                           o        h        l        c  volume  complete
time
2024-09-08 21:00:00  1.10856  1.10919  1.10347  1.10361   82539      True

In [17]:
api.get_history(instrument = "EUR_USD", start = "2024-09-09", end = "2024-09-09",
                granularity = "D", price = "B")

                           o        h        l        c  volume  complete
time
2024-09-08 21:00:00  1.10798  1.10903  1.10331  1.10343   82539      True

## Getting Historical Data (Part 2)

In [18]:
api.get_history("EUR_USD", "2021-01-09", "2024-09-09", "H1", "A")

                           o        h        l        c  volume  complete
time
2021-01-10 22:00:00  1.22240  1.22324  1.22178  1.22222     163      True
2021-01-10 23:00:00  1.22228  1.22231  1.21833  1.21880    2591      True
2021-01-11 00:00:00  1.21879  1.21969  1.21821  1.21896    2688      True
2021-01-11 01:00:00  1.21896  1.21916  1.21721  1.21786    2988      True
2021-01-11 02:00:00  1.21784  1.21810  1.21677  1.21810    2398      True
...                      ...      ...      ...      ...     ...       ...
2024-09-06 19:00:00  1.10869  1.10904  1.10831  1.10893    3272      True
2024-09-06 20:00:00  1.10895  1.10896  1.10855  1.10865    1748      True
2024-09-08 21:00:00  1.10856  1.10875  1.10840  1.10858     294      True
2024-09-08 22:00:00  1.10841  1.10914  1.10841  1.10878    1338      True
2024-09-08 23:00:00  1.10880  1.10917  1.10873  1.10874    2719      True

[22841 rows x 6 columns]

In [19]:
api.get_history("EUR_USD", "2024-09-03", "2024-09-05", "H12", "A")

                           o        h        l        c  volume  complete
time
2024-09-02 21:00:00  1.10739  1.10742  1.10489  1.10493   34664      True
2024-09-03 09:00:00  1.10494  1.10705  1.10272  1.10440   67103      True
2024-09-03 21:00:00  1.10452  1.10637  1.10407  1.10526   40263      True
2024-09-04 09:00:00  1.10527  1.10959  1.10408  1.10840   59984      True
2024-09-04 21:00:00  1.10854  1.11012  1.10755  1.10999   34402      True

In [20]:
api.get_history("EUR_USD", "2024-09-03", "2024-09-05", "M1", "A")

                           o        h        l        c  volume  complete
time
2024-09-03 00:00:00  1.10680  1.10681  1.10677  1.10680      51      True
2024-09-03 00:01:00  1.10679  1.10684  1.10669  1.10678      90      True
2024-09-03 00:02:00  1.10679  1.10679  1.10669  1.10673      78      True
2024-09-03 00:03:00  1.10672  1.10672  1.10660  1.10660      60      True
2024-09-03 00:04:00  1.10662  1.10674  1.10655  1.10674      41      True
...                      ...      ...      ...      ...     ...       ...
2024-09-04 23:55:00  1.10819  1.10821  1.10818  1.10819      32      True
2024-09-04 23:56:00  1.10819  1.10820  1.10811  1.10813      88      True
2024-09-04 23:57:00  1.10814  1.10819  1.10812  1.10819      69      True
2024-09-04 23:58:00  1.10819  1.10820  1.10817  1.10818      49      True
2024-09-04 23:59:00  1.10818  1.10820  1.10798  1.10810      51      True

[2869 rows x 6 columns]

In [21]:
api.get_history("EUR_USD", "2024-09-03", "2024-09-04", "S5", "A") # drops a Future Warning -> can be ignored for now

                           o        h        l        c  volume  complete
time
2024-09-03 00:00:00  1.10680  1.10681  1.10680  1.10680      12      True
2024-09-03 00:00:10  1.10679  1.10680  1.10679  1.10680       4      True
2024-09-03 00:00:15  1.10679  1.10681  1.10679  1.10681       8      True
2024-09-03 00:00:20  1.10681  1.10681  1.10680  1.10680       5      True
2024-09-03 00:00:25  1.10679  1.10680  1.10679  1.10679       4      True
...                      ...      ...      ...      ...     ...       ...
2024-09-03 23:59:35  1.10499  1.10500  1.10499  1.10500       2      True
2024-09-03 23:59:40  1.10501  1.10501  1.10499  1.10499       5      True
2024-09-03 23:59:45  1.10500  1.10500  1.10499  1.10499       4      True
2024-09-03 23:59:55  1.10495  1.10495  1.10493  1.10493       5      True
2024-09-04 00:00:00  1.10489  1.10489  1.10485  1.10485      15      True

[14656 rows x 6 columns]

In [22]:
api.get_instruments()

[('AUD/CAD', 'AUD_CAD'),
 ('AUD/CHF', 'AUD_CHF'),
 ('AUD/HKD', 'AUD_HKD'),
 ('AUD/JPY', 'AUD_JPY'),
 ('AUD/NZD', 'AUD_NZD'),
 ('AUD/SGD', 'AUD_SGD'),
 ('AUD/USD', 'AUD_USD'),
 ('Australia 200', 'AU200_AUD'),
 ('Bitcoin', 'BTC_USD'),
 ('Bitcoin Cash', 'BCH_USD'),
 ('Brent Crude Oil', 'BCO_USD'),
 ('Bund', 'DE10YB_EUR'),
 ('CAD/CHF', 'CAD_CHF'),
 ('CAD/HKD', 'CAD_HKD'),
 ('CAD/JPY', 'CAD_JPY'),
 ('CAD/SGD', 'CAD_SGD'),
 ('CHF/HKD', 'CHF_HKD'),
 ('CHF/JPY', 'CHF_JPY'),
 ('CHF/ZAR', 'CHF_ZAR'),
 ('China A50', 'CN50_USD'),
 ('China H Shares', 'CHINAH_HKD'),
 ('Copper', 'XCU_USD'),
 ('Corn', 'CORN_USD'),
 ('EUR/AUD', 'EUR_AUD'),
 ('EUR/CAD', 'EUR_CAD'),
 ('EUR/CHF', 'EUR_CHF'),
 ('EUR/CZK', 'EUR_CZK'),
 ('EUR/DKK', 'EUR_DKK'),
 ('EUR/GBP', 'EUR_GBP'),
 ('EUR/HKD', 'EUR_HKD'),
 ('EUR/HUF', 'EUR_HUF'),
 ('EUR/JPY', 'EUR_JPY'),
 ('EUR/NOK', 'EUR_NOK'),
 ('EUR/NZD', 'EUR_NZD'),
 ('EUR/PLN', 'EUR_PLN'),
 ('EUR/SEK', 'EUR_SEK'),
 ('EUR/SGD', 'EUR_SGD'),
 ('EUR/TRY', 'EUR_TRY'),
 ('EUR/USD', 'EUR_USD'),
 ('EUR/ZAR', 'EUR_ZAR'),
 ('Ether', 'ETH_USD'),
 ('Europe 50', 'EU50_EUR'),
 ('France 40', 'FR40_EUR'),
 ('GBP/AUD', 'GBP_AUD'),
 ('GBP/CAD', 'GBP_CAD'),
 ('GBP/CHF', 'GBP_CHF'),
 ('GBP/HKD', 'GBP_HKD'),
 ('GBP/JPY', 'GBP_JPY'),
 ('GBP/NZD', 'GBP_NZD'),
 ('GBP/PLN', 'GBP_PLN'),
 ('GBP/SGD', 'GBP_SGD'),
 ('GBP/USD', 'GBP_USD'),
 ('GBP/ZAR', 'GBP_ZAR'),
 ('Germany 30', 'DE30_EUR'),
 ('Gold', 'XAU_USD'),
 ('Gold/AUD', 'XAU_AUD'),
 ('Gold/CAD', 'XAU_CAD'),
 ('Gold/CHF', 'XAU_CHF'),
 ('Gold/EUR', 'XAU_EUR'),
 ('Gold/GBP', 'XAU_GBP'),
 ('Gold/HKD', 'XAU_HKD'),
 ('Gold/JPY', 'XAU_JPY'),
 ('Gold/NZD', 'XAU_NZD'),
 ('Gold/SGD', 'XAU_SGD'),
 ('Gold/Silver', 'XAU_XAG'),
 ('HKD/JPY', 'HKD_JPY'),
 ('Hong Kong 33', 'HK33_HKD'),
 ('Japan 225', 'JP225_USD'),
 ('Japan 225 (JPY)', 'JP225Y_JPY'),
 ('Litecoin', 'LTC_USD'),
 ('NZD/CAD', 'NZD_CAD'),
 ('NZD/CHF', 'NZD_CHF'),
 ('NZD/HKD', 'NZD_HKD'),
 ('NZD/JPY', 'NZD_JPY'),
 ('NZD/SGD', 'NZD_SGD'),
 ('NZD/USD', 'NZD_USD'),
 ('Natural Gas', 'NATGAS_USD'),
 ('Netherlands 25', 'NL25_EUR'),
 ('Palladium', 'XPD_USD'),
 ('Platinum', 'XPT_USD'),
 ('SGD/CHF', 'SGD_CHF'),
 ('SGD/JPY', 'SGD_JPY'),
 ('Silver', 'XAG_USD'),
 ('Silver/AUD', 'XAG_AUD'),
 ('Silver/CAD', 'XAG_CAD'),
 ('Silver/CHF', 'XAG_CHF'),
 ('Silver/EUR', 'XAG_EUR'),
 ('Silver/GBP', 'XAG_GBP'),
 ('Silver/HKD', 'XAG_HKD'),
 ('Silver/JPY', 'XAG_JPY'),
 ('Silver/NZD', 'XAG_NZD'),
 ('Silver/SGD', 'XAG_SGD'),
 ('Singapore 30', 'SG30_SGD'),
 ('Soybeans', 'SOYBN_USD'),
 ('Spain 35', 'ESPIX_EUR'),
 ('Sugar', 'SUGAR_USD'),
 ('Switzerland 20', 'CH20_CHF'),
 ('TRY/JPY', 'TRY_JPY'),
 ('UK 100', 'UK100_GBP'),
 ('UK 10Y Gilt', 'UK10YB_GBP'),
 ('US 10Y T-Note', 'USB10Y_USD'),
 ('US 2Y T-Note', 'USB02Y_USD'),
 ('US 5Y T-Note', 'USB05Y_USD'),
 ('US Nas 100', 'NAS100_USD'),
 ('US Russ 2000', 'US2000_USD'),
 ('US SPX 500', 'SPX500_USD'),
 ('US T-Bond', 'USB30Y_USD'),
 ('US Wall St 30', 'US30_USD'),
 ('USD/CAD', 'USD_CAD'),
 ('USD/CHF', 'USD_CHF'),
 ('USD/CNH', 'USD_CNH'),
 ('USD/CZK', 'USD_CZK'),
 ('USD/DKK', 'USD_DKK'),
 ('USD/HKD', 'USD_HKD'),
 ('USD/HUF', 'USD_HUF'),
 ('USD/JPY', 'USD_JPY'),
 ('USD/MXN', 'USD_MXN'),
 ('USD/NOK', 'USD_NOK'),
 ('USD/PLN', 'USD_PLN'),
 ('USD/SEK', 'USD_SEK'),
 ('USD/SGD', 'USD_SGD'),
 ('USD/THB', 'USD_THB'),
 ('USD/TRY', 'USD_TRY'),
 ('USD/ZAR', 'USD_ZAR'),
 ('West Texas Oil', 'WTICO_USD'),
 ('Wheat', 'WHEAT_USD'),
 ('ZAR/JPY', 'ZAR_JPY')]

In [23]:
api.get_history("SPX500_USD", "2020-08-03", "2020-08-04", "H1", "A")

                          o       h       l       c  volume  complete
time
2020-08-03 00:00:00  3272.8  3276.1  3267.0  3273.5    2094      True
2020-08-03 01:00:00  3273.8  3279.6  3271.5  3277.8    1916      True
2020-08-03 02:00:00  3278.1  3278.1  3270.5  3271.8     843      True
2020-08-03 03:00:00  3272.3  3273.8  3269.5  3270.3     482      True
2020-08-03 04:00:00  3270.6  3271.8  3268.5  3271.8     368      True
2020-08-03 05:00:00  3272.0  3275.6  3270.0  3272.4     499      True
2020-08-03 06:00:00  3272.0  3272.8  3267.3  3270.0     743      True
2020-08-03 07:00:00  3270.3  3272.3  3263.0  3272.0    1717      True
2020-08-03 08:00:00  3272.3  3275.9  3264.3  3267.8    1160      True
2020-08-03 09:00:00  3267.5  3275.3  3266.0  3275.0    1085      True
2020-08-03 10:00:00  3274.5  3288.8  3273.8  3288.0    1078      True
2020-08-03 11:00:00  3288.3  3292.0  3286.2  3291.8     697      True
2020-08-03 12:00:00  3292.3  3294.1  3290.3  3292.5     596      True
2020-08-03 13:00:00  3292.6  3293.3  3284.7  3291.0    1555      True
2020-08-03 14:00:00  3290.8  3300.0  3286.5  3289.7    1824      True
2020-08-03 15:00:00  3290.0  3301.5  3289.2  3298.2     753      True
2020-08-03 16:00:00  3298.5  3299.5  3295.0  3296.5     633      True
2020-08-03 17:00:00  3297.0  3300.0  3296.2  3298.5     566      True
2020-08-03 18:00:00  3298.8  3303.5  3296.7  3302.2     845      True
2020-08-03 19:00:00  3302.5  3303.1  3291.5  3295.2    1796      True
2020-08-03 20:00:00  3295.0  3298.6  3291.2  3297.0     643      True
2020-08-03 22:00:00  3295.8  3296.6  3293.8  3295.3     478      True
2020-08-03 23:00:00  3295.0  3298.4  3294.3  3295.8     409      True

## Streaming high-frequency real-time Data

In [24]:
import pandas as pd
import tpqoa

In [25]:
api = tpqoa.tpqoa("oanda.cfg")

In [26]:
api.stream_data('EUR_USD', stop = 10)
# api.stream_data('EUR_USD')

2025-12-17T09:29:15.051843470Z 1.1715 1.1716
2025-12-17T09:29:16.371772717Z 1.17151 1.1716
2025-12-17T09:29:17.258454935Z 1.17151 1.17161
2025-12-17T09:29:17.482486550Z 1.17151 1.17162
2025-12-17T09:29:18.480885098Z 1.17151 1.17161
2025-12-17T09:29:19.031067067Z 1.1715 1.17161
2025-12-17T09:29:19.759292591Z 1.17146 1.17157
2025-12-17T09:29:20.424338255Z 1.17146 1.17157
2025-12-17T09:29:20.573535432Z 1.17146 1.17156
2025-12-17T09:29:21.074720171Z 1.17145 1.17156

In [27]:
api.stop_stream()

TypeError: 'bool' object is not callable

## Creating Orders and Executing Trades

In [ ]:
import pandas as pd
import tpqoa

In [ ]:
api = tpqoa.tpqoa("oanda.cfg")

In [ ]:
api.create_order(instrument = "EUR_USD", units = 99000, sl_distance= 0.1)

In [ ]:
api.create_order(instrument = "EUR_USD", units = -99000, sl_distance= 0.1)

In [ ]:
api.get_account_summary()

In [ ]:
api.get_transactions(tid = 1) # insert the id of the first trade in this session

In [ ]:
api.print_transactions(tid = 1) # insert the id of the first trade in this session